version: '3'

services:
    eureka-server:
      image:  tarunmt/eureka-discovery-service
      ports:
        - "8761:8761"

    news-management:
      image:  tarunmt/news-management
      ports:
        - "8001:8001"

        
    user-management-service:
      image:  tarunmt/user-management-service	
      ports:
        - "8005:8005"
     
                
    spring-gateway:
      image:  tarunmt/spring-gateway	
      ports:
        - "8090:8090"
      depends_on: 
        - news-management
        - user-management-service

 
    